# Generated by Django 5.1.3 on 2025-04-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buttonclick',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.button'),
        ),
        migrations.CreateModel(
            name='DefaultButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('button_label', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='board_buttons/images/')),
                ('category', models.JSONField(default=list, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.defaultboard')),
            ],
        ),
        migrations.AddField(
            model_name='buttonclick',
            name='default_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.defaultbutton'),
        ),
    ]
