# Generated by Django 5.1.3 on 2025-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_buttonclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='category',
            field=models.JSONField(default=None),
        ),
    ]
