# Generated by Django 5.1.3 on 2025-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_button_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
