# Generated by Django 5.1.3 on 2025-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
        migrations.AddField(
            model_name='button',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
