# Generated by Django 4.2.4 on 2025-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_board_description_button_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='category',
            field=models.JSONField(default=list, null=True),
        ),
    ]
