# Generated by Django 5.1.3 on 2025-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_button_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
